name: hakari
description: Simple & Cool Benchmark Tool for Dart.
version: 0.0.1
homepage: https://github.com/obutora/hakari

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  ansicolor: ^2.0.1
  flutter:
    sdk: flutter
  vm_service: ^11.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
